### PR TITLE
Feature/landing courses

### PR DESCRIPTION
**Pull request by Portero20**
## ¿Que tipos de cambios has hecho? (selecciona varios si hace falta)

- [x] Refactor
- [x] Feature
- [ ] Bug FIx
- [x] Optimización
- [ ] Documentación

## Descripción

- Modification of the database seed to include detailed information about each of the NOC incubator courses, along with addition of new attributes.
- Update the course interface to reflect the changes in the data.
- Update of the course routing to handle the new data structure.
- Update of the course endpoint; now, we only consume a single endpoint that includes both the Courses table and course details (courseDetaisl).
- Add a new method in the courses.service.ts to calculate the completion date of a course that is in progress.

## Link Tarea/s

[Corregir los endpoints que se consumieron en el proyecto.](https://trello.com/c/pSZqiCFT)

## Capturas, Videos, Instrucciones QA

[Course details view](https://postimg.cc/w1CPZvgk)

[Landing page view](https://postimg.cc/5Y0wmBTK)

## Checklist

- [x] Tested the database seed modification, incluiding detailed information about each the NOC Incubator courses and the addition of new attributes.
- [x] Tested the update of the course interface to reflect the changes in the data.
- [x] Tested the update of the course routing to handle the new data structure.
- [x] Tested the update of the course endpoint to consume a single endpoint including both the Courses table and course details (courseDetails).
- [x] Tested the new method added in courses.service.ts to calculate the completion date of a course that is in progress.

### CODE REVIEW

**Comment by JulioMartin12** [comment]
Checked all changes, all OK

**Comment by JulioMartin12** [comment]
Checked all changes, all OK

**Comment by cgavernet** [comment]
All changes verified, everything ok

**Review by cgavernet — APPROVED** [review]
All changes verified, everything ok

**Pull request merged**
